# -*- coding: utf-8 -*-
"""Generating Word Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0E9ilalTSJ_-1ifMqd2igSglVA5YtJ8
"""



import sys
!{sys.executable} -m pip install kagglehub

import kagglehub
import os

# Download the dataset
path = kagglehub.dataset_download("timothyabwao/wordcloud-masks")
print(f"Dataset downloaded to: {path}")

# List files in the downloaded directory to identify the text file
file_list = os.listdir(path)
print(f"Files in the dataset directory: {file_list}")

# Assuming there's a text file, let's try to find one and read it
text_file = None
for f in file_list:
    if f.endswith('.txt'): # Adjust this if the text is in a different format
        text_file = os.path.join(path, f)
        break

if text_file:
    with open(text_file, 'r', encoding='utf-8') as f:
        kaggle_text_data = f.read()
    print(f"Successfully loaded text from {text_file}")
else:
    print("No .txt file found in the dataset. Please specify which file to use for the word cloud.")
    kaggle_text_data = ""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Use the text data loaded from Kaggle
if kaggle_text_data:
    text_to_use = kaggle_text_data
else:
    # Fallback to sample text if no Kaggle text was loaded
    text_to_use = "This is a fallback sample text because no data was loaded from Kaggle. Please check the dataset for text files."

# Create a WordCloud object
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_to_use)

# Display the generated image:
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

import sys
!{sys.executable} -m pip install wordcloud matplotlib

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Sample text data (replace with your own text data)
text_data = "This is a sample text for generating a word cloud. Word clouds are great for visualizing text data and seeing the most frequent words. Python libraries like wordcloud make it easy to create beautiful visualizations."

# Create a WordCloud object
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_data)

# Display the generated image:
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()